# Generated by Django 3.0.5 on 2020-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=700, null=True, verbose_name='Conteúdo da mensagem'),
        ),
    ]
